# Generated by Django 4.0.3 on 2022-03-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anouncement', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999999)),
                ('group_of', models.IntegerField()),
                ('project', models.CharField(max_length=999999)),
                ('project_description', models.TextField(max_length=9999999)),
                ('mean_age', models.IntegerField()),
                ('leader_name', models.CharField(max_length=999999)),
                ('leader_age', models.IntegerField()),
                ('expected_profit_per_week', models.IntegerField()),
                ('needs', models.TextField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('revenue', models.IntegerField()),
                ('expense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=999999)),
                ('repo', models.CharField(blank=True, max_length=999999)),
                ('job_title', models.CharField(max_length=999999, unique=True)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=999999)),
                ('todo_title', models.CharField(max_length=999999)),
                ('due_at', models.DateField()),
                ('remind_before_days', models.IntegerField()),
            ],
        ),
    ]
