# Generated by Django 4.0 on 2022-01-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anouncement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='blocked_ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sus_ips', models.CharField(max_length=16)),
            ],
        ),
    ]
