# Generated by Django 4.0 on 2022-01-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ips',
            new_name='ip',
        ),
    ]
