# Generated by Django 4.0 on 2022-02-06 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userjobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserJobs',
            new_name='UserJob',
        ),
    ]
