# Generated by Django 4.0 on 2022-03-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_earning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('month', models.IntegerField(unique=True)),
                ('day', models.IntegerField(unique=True)),
                ('revenue', models.IntegerField()),
                ('expense', models.IntegerField()),
            ],
        ),
    ]
