# Generated by Django 4.0 on 2022-01-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ips_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='blocked_ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sus_ips', models.CharField(max_length=16)),
            ],
        ),
    ]
