# Generated by Django 4.0 on 2022-02-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_userjobs_userjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjob',
            name='repo',
            field=models.CharField(blank=True, max_length=999999),
        ),
    ]
