# Generated by Django 4.0 on 2022-01-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blocked_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.CharField(max_length=256)),
                ('from_whom', models.CharField(max_length=256)),
                ('message', models.TextField(max_length=999999999)),
                ('html', models.TextField()),
            ],
        ),
    ]
