# Generated by Django 4.0 on 2022-03-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_earning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Earning',
        ),
        migrations.DeleteModel(
            name='UserTodo',
        ),
    ]
