# Generated by Django 4.0 on 2022-03-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_earning_delete_usertodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True)),
                ('revenue', models.IntegerField()),
                ('expense', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=999999)),
                ('todo_title', models.CharField(max_length=999999)),
                ('due_at', models.DateField(auto_now=True)),
                ('remind_before_days', models.IntegerField()),
            ],
        ),
    ]
