# Generated by Django 4.0 on 2022-01-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sentmail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentMail',
        ),
    ]
