# Generated by Django 4.0 on 2022-03-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userjob_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999999)),
                ('group_of', models.IntegerField()),
                ('project', models.CharField(max_length=999999)),
                ('project_description', models.TextField(max_length=9999999)),
                ('mean_age', models.IntegerField()),
                ('leader_name', models.CharField(max_length=999999)),
                ('leader_age', models.IntegerField()),
                ('expected_profit_per_week', models.IntegerField()),
                ('needs', models.TextField(max_length=999999)),
            ],
        ),
    ]
