# Generated by Django 4.0 on 2022-03-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_earning_usertodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='due_at',
            field=models.DateField(),
        ),
    ]
