# Generated by Django 4.0 on 2022-03-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='anouncement',
            field=models.TextField(blank=True),
        ),
    ]
