# Generated by Django 4.0 on 2022-01-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_sentmail'),
        ('app', '0006_delete_ip'),
    ]

    operations = [
    ]
