# Generated by Django 4.0 on 2022-01-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SentMail',
        ),
    ]
