# Generated by Django 4.0 on 2022-03-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_earning_day_alter_usertodo_due_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJob',
        ),
    ]
