# Generated by Django 4.0 on 2022-03-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=999999)),
                ('salary_percentage', models.IntegerField()),
            ],
        ),
    ]
