# Generated by Django 4.0 on 2022-03-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jobsalary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJob',
        ),
    ]
