# Generated by Django 4.0.3 on 2022-03-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSalary',
        ),
    ]
