# Generated by Django 4.0.3 on 2022-03-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_jobsalary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJob',
        ),
    ]
