# Generated by Django 4.0.3 on 2022-03-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_blocked_ip_delete_userjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=999999)),
                ('repo', models.CharField(blank=True, max_length=999999)),
                ('job_title', models.CharField(max_length=999999, unique=True)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
