# Generated by Django 4.0 on 2022-01-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='is_in_trash',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
