# Generated by Django 4.0 on 2022-01-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmail',
            name='html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='message',
            field=models.TextField(blank=True, max_length=999999999),
        ),
    ]

# Lawyer won't see this file
