# Generated by Django 4.0 on 2022-01-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_sentmail_is_in_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='message_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
